version: '3.8'
services:
  postgres-db:
    image: postgres:16
    container_name: talentstream_db
    command: postgres -c timezone=UTC
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: talentstream
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: