global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'talentstream-backend-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'talentstream-ai-python'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']