apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:latest
          command: [ 'sh', '-c', "until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done" ]
        - name: wait-for-java
          image: busybox:latest
          command: [ 'sh', '-c', "until nc -z backend-java 8080; do echo waiting for java; sleep 2; done" ]
      containers:
        - name: ai-service
          image: acepk7/talentstream-ai-service:latest
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: BACKEND_URL
              value: "http://backend-java:8080"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
            - name: M2M_CLIENT_ID
              value: "ai-vector-engine-v1"
            - name: M2M_CLIENT_SECRET
              value: "super-secret-cryptographic-key-change-in-prod"
            - name: JAVA_BACKEND_DIR
              value: "/app"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: shared-uploads-pvc